const ASSEMBLY_STUB: &str = "
; auto-generated by mamba
global _main
";

const DATA_STUB: &str = "
section .data
";

const TEXT_STUB: &str = "
section .text
";

const SYS_WRITE: &str = "
sys_write:
    mov rax, 0x02000004
    mov rdi, 1
    
";